# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94d00fcb63667a14b66853e17a8100b4d8eb6ab7ee68aaf9c35bcc39816e3320f217e0faffcc58f135c3b6a58be37ec4449ab4aa2ec54150d246708dc7155011

test:
  secret_key_base: 3a7554508e894fac4f25d771a16e07afc32bc7a353b4528d49aaae9c43453c13bfbe9ec5037727506e12b741dbcd953a8313096d014ccdbe0b093f6c80190311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
